// Hyrox data
export const hyroxData = [
  {
    clase: "6AM",
    nombre: "Mary",
    tiempo: "20:43",
    tiempo_segs: 1243,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 1,
    ranking_por_sexo: "F1",
    delta_vs_1_min: 0.0,
    delta_vs_anterior_min: 0.0,
  },
  {
    clase: "4PM",
    nombre: "Luigi",
    tiempo: "22:56",
    tiempo_segs: 1376,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 2,
    ranking_por_sexo: "M1",
    delta_vs_1_min: 2.22,
    delta_vs_anterior_min: 2.22,
  },
  {
    clase: "5PM",
    nombre: "Walter 5PM",
    tiempo: "27:58",
    tiempo_segs: 1678,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 3,
    ranking_por_sexo: "M2",
    delta_vs_1_min: 7.25,
    delta_vs_anterior_min: 5.03,
  },
  {
    clase: "5PM",
    nombre: "Jesus",
    tiempo: "29:30",
    tiempo_segs: 1770,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 4,
    ranking_por_sexo: "M3",
    delta_vs_1_min: 8.78,
    delta_vs_anterior_min: 1.53,
  },
  {
    clase: "6AM",
    nombre: "Luisa",
    tiempo: "31:33",
    tiempo_segs: 1893,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 5,
    ranking_por_sexo: "F2",
    delta_vs_1_min: 10.83,
    delta_vs_anterior_min: 2.05,
  },
  {
    clase: "4PM",
    nombre: "Valerie",
    tiempo: "32:30",
    tiempo_segs: 1950,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 6,
    ranking_por_sexo: "F3",
    delta_vs_1_min: 11.78,
    delta_vs_anterior_min: 0.95,
  },
  {
    clase: "4PM",
    nombre: "Alfredo 4PM",
    tiempo: "33:04",
    tiempo_segs: 1984,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 7,
    ranking_por_sexo: "M4",
    delta_vs_1_min: 12.35,
    delta_vs_anterior_min: 0.57,
  },
  {
    clase: "5AM",
    nombre: "Gustavo",
    tiempo: "33:10",
    tiempo_segs: 1990,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 8,
    ranking_por_sexo: "M5",
    delta_vs_1_min: 12.45,
    delta_vs_anterior_min: 0.1,
  },
  {
    clase: "5AM",
    nombre: "Pablo",
    tiempo: "33:20",
    tiempo_segs: 2000,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 9,
    ranking_por_sexo: "M6",
    delta_vs_1_min: 12.62,
    delta_vs_anterior_min: 0.17,
  },
  {
    clase: "5AM",
    nombre: "Leidy",
    tiempo: "33:40",
    tiempo_segs: 2020,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 10,
    ranking_por_sexo: "F4",
    delta_vs_1_min: 12.95,
    delta_vs_anterior_min: 0.33,
  },
  {
    clase: "6AM",
    nombre: "Alfredo 6AM",
    tiempo: "34:00",
    tiempo_segs: 2040,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 11,
    ranking_por_sexo: "M7",
    delta_vs_1_min: 13.28,
    delta_vs_anterior_min: 0.33,
  },
  {
    clase: "7PM",
    nombre: "Nikolas",
    tiempo: "34:17",
    tiempo_segs: 2057,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 12,
    ranking_por_sexo: "M8",
    delta_vs_1_min: 13.57,
    delta_vs_anterior_min: 0.28,
  },
  {
    clase: "5AM",
    nombre: "Kelly",
    tiempo: "34:20",
    tiempo_segs: 2060,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 13,
    ranking_por_sexo: "F5",
    delta_vs_1_min: 13.62,
    delta_vs_anterior_min: 0.05,
  },
  {
    clase: "5AM",
    nombre: "Jose M.",
    tiempo: "34:33",
    tiempo_segs: 2073,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 14,
    ranking_por_sexo: "M9",
    delta_vs_1_min: 13.83,
    delta_vs_anterior_min: 0.22,
  },
  {
    clase: "5AM",
    nombre: "Jose 5AM",
    tiempo: "34:34",
    tiempo_segs: 2074,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 15,
    ranking_por_sexo: "M10",
    delta_vs_1_min: 13.85,
    delta_vs_anterior_min: 0.02,
  },
  {
    clase: "5PM",
    nombre: "Andrea",
    tiempo: "34:56",
    tiempo_segs: 2096,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 16,
    ranking_por_sexo: "F6",
    delta_vs_1_min: 14.22,
    delta_vs_anterior_min: 0.37,
  },
  {
    clase: "4PM",
    nombre: "Valentina 4PM",
    tiempo: "34:59",
    tiempo_segs: 2099,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 17,
    ranking_por_sexo: "F7",
    delta_vs_1_min: 14.27,
    delta_vs_anterior_min: 0.05,
  },
  {
    clase: "7PM",
    nombre: "Gabriela",
    tiempo: "35:07",
    tiempo_segs: 2107,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 18,
    ranking_por_sexo: "F8",
    delta_vs_1_min: 14.4,
    delta_vs_anterior_min: 0.13,
  },
  {
    clase: "5AM",
    nombre: "Jaime",
    tiempo: "35:20",
    tiempo_segs: 2120,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 19,
    ranking_por_sexo: "M11",
    delta_vs_1_min: 14.62,
    delta_vs_anterior_min: 0.22,
  },
  {
    clase: "7PM",
    nombre: "Irina",
    tiempo: "35:23",
    tiempo_segs: 2123,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 20,
    ranking_por_sexo: "F9",
    delta_vs_1_min: 14.67,
    delta_vs_anterior_min: 0.05,
  },
  {
    clase: "6AM",
    nombre: "Samir",
    tiempo: "35:24",
    tiempo_segs: 2124,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 21,
    ranking_por_sexo: "M12",
    delta_vs_1_min: 14.68,
    delta_vs_anterior_min: 0.02,
  },
  {
    clase: "8PM",
    nombre: "Luis",
    tiempo: "35:52",
    tiempo_segs: 2152,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 22,
    ranking_por_sexo: "M13",
    delta_vs_1_min: 15.15,
    delta_vs_anterior_min: 0.47,
  },
  {
    clase: "5AM",
    nombre: "Angela",
    tiempo: "36:10",
    tiempo_segs: 2170,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 23,
    ranking_por_sexo: "F10",
    delta_vs_1_min: 15.45,
    delta_vs_anterior_min: 0.3,
  },
  {
    clase: "5AM",
    nombre: "Daniel",
    tiempo: "36:20",
    tiempo_segs: 2180,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 24,
    ranking_por_sexo: "M14",
    delta_vs_1_min: 15.62,
    delta_vs_anterior_min: 0.17,
  },
  {
    clase: "7PM",
    nombre: "Oscar 7PM",
    tiempo: "37:24",
    tiempo_segs: 2244,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 25,
    ranking_por_sexo: "M15",
    delta_vs_1_min: 16.68,
    delta_vs_anterior_min: 1.07,
  },
  {
    clase: "7PM",
    nombre: "Tomy",
    tiempo: "37:33",
    tiempo_segs: 2253,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 26,
    ranking_por_sexo: "M16",
    delta_vs_1_min: 16.83,
    delta_vs_anterior_min: 0.15,
  },
  {
    clase: "7AM",
    nombre: "Valeria T.C",
    tiempo: "37:50",
    tiempo_segs: 2270,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 27,
    ranking_por_sexo: "F11",
    delta_vs_1_min: 17.12,
    delta_vs_anterior_min: 0.28,
  },
  {
    clase: "6AM",
    nombre: "Jose 6AM-2",
    tiempo: "38:45",
    tiempo_segs: 2325,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 28,
    ranking_por_sexo: "M17",
    delta_vs_1_min: 18.03,
    delta_vs_anterior_min: 0.92,
  },
  {
    clase: "8AM",
    nombre: "Farid",
    tiempo: "38:50",
    tiempo_segs: 2330,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 29,
    ranking_por_sexo: "M18",
    delta_vs_1_min: 18.12,
    delta_vs_anterior_min: 0.08,
  },
  {
    clase: "6AM",
    nombre: "Valentina 6AM",
    tiempo: "38:58",
    tiempo_segs: 2338,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 30,
    ranking_por_sexo: "F12",
    delta_vs_1_min: 18.25,
    delta_vs_anterior_min: 0.13,
  },
  {
    clase: "5AM",
    nombre: "Cristina 5AM",
    tiempo: "39:22",
    tiempo_segs: 2362,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 31,
    ranking_por_sexo: "F13",
    delta_vs_1_min: 18.65,
    delta_vs_anterior_min: 0.4,
  },
  {
    clase: "6AM",
    nombre: "Nicoll",
    tiempo: "39:23",
    tiempo_segs: 2363,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 32,
    ranking_por_sexo: "F14",
    delta_vs_1_min: 18.67,
    delta_vs_anterior_min: 0.02,
  },
  {
    clase: "7PM",
    nombre: "Jermy",
    tiempo: "39:33",
    tiempo_segs: 2373,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 33,
    ranking_por_sexo: "M19",
    delta_vs_1_min: 18.83,
    delta_vs_anterior_min: 0.17,
  },
  {
    clase: "8AM",
    nombre: "Claudia",
    tiempo: "39:47",
    tiempo_segs: 2387,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 34,
    ranking_por_sexo: "F15",
    delta_vs_1_min: 19.07,
    delta_vs_anterior_min: 0.23,
  },
  {
    clase: "6AM",
    nombre: "Jose 6AM-1",
    tiempo: "39:53",
    tiempo_segs: 2393,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 35,
    ranking_por_sexo: "M20",
    delta_vs_1_min: 19.17,
    delta_vs_anterior_min: 0.1,
  },
  {
    clase: "6AM",
    nombre: "Stephy",
    tiempo: "39:58",
    tiempo_segs: 2398,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 36,
    ranking_por_sexo: "F16",
    delta_vs_1_min: 19.25,
    delta_vs_anterior_min: 0.08,
  },
  {
    clase: "5AM",
    nombre: "Milena",
    tiempo: "40:00",
    tiempo_segs: 2400,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 37,
    ranking_por_sexo: "F17",
    delta_vs_1_min: 19.28,
    delta_vs_anterior_min: 0.03,
  },
  {
    clase: "5AM",
    nombre: "Carlos",
    tiempo: "40:00",
    tiempo_segs: 2400,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: 38,
    ranking_por_sexo: "M21",
    delta_vs_1_min: 19.28,
    delta_vs_anterior_min: 0.0,
  },
  {
    clase: "6AM",
    nombre: "Carly",
    tiempo: "40:00",
    tiempo_segs: 2400,
    termino: "Sí",
    ultimo_workout: "20cal",
    genero: "F",
    ranking_general: 39,
    ranking_por_sexo: "F18",
    delta_vs_1_min: 19.28,
    delta_vs_anterior_min: 0.0,
  },
  {
    clase: "5AM",
    nombre: "Andres",
    tiempo: "",
    tiempo_segs: null,
    termino: "No",
    ultimo_workout: "8cal",
    genero: "M",
    ranking_general: null,
    ranking_por_sexo: null,
    delta_vs_1_min: null,
    delta_vs_anterior_min: null,
  },
  {
    clase: "5AM",
    nombre: "Walter 5AM",
    tiempo: "",
    tiempo_segs: null,
    termino: "No",
    ultimo_workout: "12cal",
    genero: "M",
    ranking_general: null,
    ranking_por_sexo: null,
    delta_vs_1_min: null,
    delta_vs_anterior_min: null,
  },
  {
    clase: "5PM",
    nombre: "Santiago",
    tiempo: "",
    tiempo_segs: null,
    termino: "No",
    ultimo_workout: "12cal",
    genero: "M",
    ranking_general: null,
    ranking_por_sexo: null,
    delta_vs_1_min: null,
    delta_vs_anterior_min: null,
  },
  {
    clase: "7PM",
    nombre: "Said",
    tiempo: "",
    tiempo_segs: null,
    termino: "No",
    ultimo_workout: "16cal",
    genero: "M",
    ranking_general: null,
    ranking_por_sexo: null,
    delta_vs_1_min: null,
    delta_vs_anterior_min: null,
  },
  {
    clase: "4PM",
    nombre: "Oscar 4PM",
    tiempo: "",
    tiempo_segs: null,
    termino: "No",
    ultimo_workout: "20cal",
    genero: "M",
    ranking_general: null,
    ranking_por_sexo: null,
    delta_vs_1_min: null,
    delta_vs_anterior_min: null,
  },
  {
    clase: "5PM",
    nombre: "Zulgenis",
    tiempo: "",
    tiempo_segs: null,
    termino: "No",
    ultimo_workout: "30mbs",
    genero: "F",
    ranking_general: null,
    ranking_por_sexo: null,
    delta_vs_1_min: null,
    delta_vs_anterior_min: null,
  },
  {
    clase: "9AM",
    nombre: "Annie",
    tiempo: "",
    tiempo_segs: null,
    termino: "No",
    ultimo_workout: "200m",
    genero: "F",
    ranking_general: null,
    ranking_por_sexo: null,
    delta_vs_1_min: null,
    delta_vs_anterior_min: null,
  },
  {
    clase: "8PM",
    nombre: "Cristian",
    tiempo: "",
    tiempo_segs: null,
    termino: "No",
    ultimo_workout: "?",
    genero: "M",
    ranking_general: null,
    ranking_por_sexo: null,
    delta_vs_1_min: null,
    delta_vs_anterior_min: null,
  },
  {
    clase: "8PM",
    nombre: "Juan",
    tiempo: "",
    tiempo_segs: null,
    termino: "No",
    ultimo_workout: "?",
    genero: "M",
    ranking_general: null,
    ranking_por_sexo: null,
    delta_vs_1_min: null,
    delta_vs_anterior_min: null,
  },
]

